### ISSUE TITLE
Error in Docker Build

### ISSUE THREAD

**Issue by r-cemper** [LEADNorthLLC/iris-ccd-devtools#2]
#19 31.88 Compiling routine CCD.Visualizer.Model.Record.1
#19 31.90 Compiling routine CCD.Visualizer.REST.ServiceMap.1
#19 31.90 ERROR: CCD.Visualizer.REST.ServiceMap.cls
#19 31.90 ERROR:  CCD.Visualizer.REST.ServiceMap.1(55) : MPP5655 : Parameter 'HTTP200STATUSOK' does not exist
#19 31.90  TEXT:                Set %response.Status = ..#HTTP200STATUSOK
#19 31.90 ERROR: CCD.Visualizer.REST.ServiceMap.cls
#19 31.90 ERROR:  CCD.Visualizer.REST.ServiceMap.1(60) : MPP5655 : Parameter 'HTTP200STATUSOK' does not exist
#19 31.90  TEXT:        Set %response.Status = ..#HTTP200STATUSOK
#19 31.90 ERROR: CCD.Visualizer.REST.ServiceMap.cls
#19 31.90 ERROR:  CCD.Visualizer.REST.ServiceMap.1(60) : MPP5655 : Parameter 'HTTP200STATUSOK' does not exist
#19 31.90  TEXT:                Set %response.Status = ..#HTTP200STATUSOK
#19 31.94 Detected 3 errors during compilation in 0.676s.
#19 31.94
#19 31.94 ERROR #5475: Error compiling routine: CCD.Visualizer.REST.ServiceMap.  Errors:  CCD.Visualizer.REST.ServiceMap.cls
#19 31.94 ERROR:  CCD.Visualizer.REST.ServiceMap.1(55) : MPP5655 : Parameter 'HTTP200STATUSOK' does not exist
#19 31.94  TEXT:                Set %response.Status = ..#HTTP200STATUSOK
#19 31.94 Detected 3 errors during load.
#19 31.94 2024-09-21 21:59:19 0 App.Installer: ERROR #5475: Error compiling routine: CCD.Visualizer.REST.ServiceMap.  Errors:  CCD.Visualizer.REST.ServiceMap.cls
#19 31.94 ERROR:  CCD.Visualizer.REST.ServiceMap.1(55) : MPP5655 : Parameter 'HTTP200STATUSOK' does not exist
#19 31.94  TEXT:                Set %response.Status = ..#HTTP200STATUSOK
#19 31.97 2024-09-21 21:59:19 0 App.Installer: ERROR #ConfigFailed: Unknown status code: <Ins>ConfigFailed )
#19 31.97   > ERROR #5475: Error compiling routine: CCD.Visualizer.REST.ServiceMap.  Errors:  CCD.Visualizer.REST.ServiceMap.cls
#19 31.97 ERROR:  CCD.Visualizer.REST.ServiceMap.1(55) : MPP5655 : Parameter 'HTTP200STATUSOK' does not exist
#19 31.97  TEXT:                Set %response.Status = ..#HTTP200STATUSOK
#19 31.97 2024-09-21 21:59:19 0 App.Installer: Installation failed at 2024-09-21 21:59:19
#19 31.97 2024-09-21 21:59:19 0 %Installer: Elapsed time 2.278806s
#19 31.97 Create web application ...1Web application /csp/visualizer/service has been created!

**Comment by chi-leadnorth** [comment]
Thanks for the info - the use of the Parameter for HTTP status were deprecated. The usage has been updated to use the numeric values for statuses and the compile errors cleared.
